version: '3'
services:
  golang:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - .:/app
    ports:
    - 8080:8080
    depends_on:
    - db

  db:
    image: mysql:5.7
    ports:
    - 3306:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysql

volumes:
  mysql-data: